# Copyright (c) the JPEG XL Project
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

# Build an Ubuntu-based docker image for aarch64 with the installed software
# needed to run JPEG XL. This is only useful when running on actual aarch64
# hardware.

FROM arm64v8/ubuntu:bionic

# Set a prompt for when using it locally.
ENV PS1="\[\033[01;33m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

RUN set -ex; \
  apt-get update -y; \
  apt-get install -y \
    bsdmainutils \
    cmake \
    curl \
    extra-cmake-modules \
    git \
    libjpeg8 \
    libgif7 \
    libpng16-16 \
    libqt5x11extras5 \
    libsdl2-2.0-0 \
    parallel; \
  rm -rf /var/lib/apt/lists/*;
