#undef EXTERN_C
#undef Private
#undef Public
#undef Export
#undef DEPRECATED
#undef Threads_Export
#undef Inline
#undef Static
#undef Delegate
#undef Union
#undef UnionNamed
#undef Struct
#undef StructDef
#undef StructDef2
#undef InlineStruct
#undef NamedInlineStruct
#undef Class
#undef ClassDef
#undef InlineClass
#undef Type
#undef TypeDef
#undef MemberWithValue
#undef Member
#undef FixedArray
#undef Method
#undef BodyMethod
#undef Constructor
#undef Property
#undef ReadOnlyProperty
#undef Enum
#undef EnumDef
#undef Value
#undef DefinedValue
#undef TypedEnum
#undef TypedValue
#undef RawCode