#undef EXTERN_C
#undef Private
#undef Public
#undef Export
#undef DEPRECATED
#undef Threads_Export
#undef Inline
#undef Static
#undef Delegate
#undef Struct
#undef StructDef
#undef StructDef2
#undef InlineStruct
#undef NamedInlineStruct
#undef Type
#undef TypeDef
#undef MemberWithValue
#undef Member
#undef FixedArray
#undef Method
#undef BodyMethod
#undef Enum
#undef EnumDef
#undef Value
#undef DefinedValue
#undef RawCode
