# Copyright (c) the JPEG XL Project Authors. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: ${{ github.event_name != 'pull_request' && 'github-pages' || '' }}
      url: ${{ github.event_name != 'pull_request' && steps.deployment.outputs.page_url || '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 2

      - name: Install build deps
        run: |
          sudo ./tools/scripts/install_deps.sh docs

      - name: Sphinx dependencies
        run: |
          pip install -r doc/sphinx/requirements.txt

      - name: Build
        run: |
          cmake -B build doc
          cmake --build build -- rtd-html

      - name: Setup Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './build/rtd'

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
